data:
  dir: './data'
  nfeat: 129
  nlabel: 2

diffusion:
  method: Gaussian
  step: 40
  s: 0.008

model:
  nhid: 32
  cat_mode: False
  skip: False
  num_layers: 2
  num_linears: 2
  output_dir: './out_models/'

train:
  num_epochs: 15000
  print_interval: 100
  time_batch: 16
  batch: 32
  block_size: 400
  lr: 0.005
  lr_schedule: True
  weight_decay: 0
  lr_decay: 0.9999999
  eps: 1.0e-5
  unweighted_MSE: True
  grad_norm: 0.1

